# Generated by Django 3.0.6 on 2020-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('code', models.PositiveSmallIntegerField()),
                ('descFile', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=103)),
                ('courses', models.ManyToManyField(to='databaseInterface.Course')),
            ],
        ),
    ]
