# Generated by Django 3.0.6 on 2020-05-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.ManyToManyField(to='databaseInterface.Chapter'),
        ),
    ]
